### ISSUE TITLE
There is a new version of Firebase Auth

### ISSUE THREAD

**Issue by alectogeek** [GameWorkstore/com.google.firebase.auth#1]
There is an update of Android SDK fixing a serious reCaptcha vulnerability.
The update of unity lib was published on February 13th.
It would be great to update current repository as well

**Comment by andnoonesthere** [comment]
Done.

**Comment by alectogeek** [comment]
I'm getting an error now
<img width="372" alt="image" src="https://github.com/GameWorkstore/com.google.firebase.auth/assets/18165303/8550d623-e6fc-47a9-906c-cec33b76b95b">

**Comment by andnoonesthere** [comment]
I've just tried to make a build with it and there were no issues. Have you run **Assets->External Dependency Manager->Android Resolver->Force Resolve** before making a build?
